# Generated by Django 2.1 on 2018-09-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20180906_1105'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post2',
            new_name='newaccount',
        ),
    ]
