# Generated by Django 2.1 on 2018-09-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_newaccount1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newaccount',
        ),
    ]
