# Generated by Django 2.1 on 2018-10-29 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_image_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post12',
        ),
    ]
