# Generated by Django 2.1 on 2018-10-29 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20181029_1218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Image1',
        ),
    ]
