# Generated by Django 2.1 on 2018-10-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20181029_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image1',
            new_name='Image2',
        ),
    ]
