# Generated by Django 2.1.5 on 2019-01-22 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_imageupload1_post13'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imageupload1',
        ),
        migrations.AlterModelTable(
            name='imageupload',
            table=None,
        ),
    ]
