# Generated by Django 2.1.5 on 2019-01-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20190122_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imageupload1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
