# Generated by Django 2.1.5 on 2019-02-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_imageupload1'),
    ]

    operations = [
        migrations.CreateModel(
            name='upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedname', models.CharField(max_length=200)),
                ('counts', models.CharField(max_length=200)),
                ('ownername', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('aadharcard', models.CharField(max_length=200)),
                ('phonenumber', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('animaltype', models.CharField(max_length=200)),
                ('img1', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
